"""empty message

Revision ID: e63339ef58fa
Revises: 03b4e975b952
Create Date: 2025-04-30 04:27:11.657438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e63339ef58fa'
down_revision = '03b4e975b952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False, foreign_key='user.id'))
        batch_op.add_column(sa.Column('character_id', sa.Integer(), nullable=False, foreign_key='characters.id'))
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=False, foreign_key='planets.id'))
        batch_op.drop_constraint('favorites_login_key', type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('login')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('login', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('favorites_login_key', ['login'])
        batch_op.drop_column('planet_id')
        batch_op.drop_column('character_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
